artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://github.com/Darpan-Maurya/Bike_Sharing_Prediction/raw/main/dataset/day.csv
  local_data_file: artifacts/data_ingestion/data
 
data_preprocessing:
  root_dir: artifacts/data_preprocessing
  data_path: artifacts/data_ingestion/data
  transformed_train_path: artifacts/data_preprocessing/train.csv
  transformed_test_path: artifacts/data_preprocessing/test.csv
  preprocessor_obj_path: artifacts/data_preprocessing/preprocessor.pkl

training:
  root_dir: artifacts/training
  transformed_train_path: artifacts/data_preprocessing/train.csv
  model_path: artifacts/training/model.pkl

evaluation:
  root_dir: artifacts/evaluation
  test_data_path: artifacts/data_preprocessing/test.csv
  model_path: artifacts/training/model.pkl
  metrics_path: artifacts/evaluation/metrics.json
